import './globals.css'
import {Roboto} from 'next/font/google'

const roboto = Roboto({subsets: ['latin'], weight: ['300', '400', '700']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={roboto.className}>
        <main className="max-w-xl mx-auto border">
            {children}
        </main >
        </body>
        </html>
    )
}
